{{- range .Values.certificates }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  commonName: {{ .commonName | quote }}
  dnsNames:
    {{- toYaml .dnsNames | nindent 4 }}
  issuerRef:
    name: {{ $.Values.issuer.name | quote }}
    kind: {{ $.Values.issuer.kind | quote }}
  secretName: {{ .secretName | quote }}
{{- end }}
