---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  refreshInterval: {{ .Values.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.secretStoreRef.name | quote }}
    kind: {{ .Values.secretStoreRef.kind | quote }}
  target:
    name: cloud-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        cloud: |
          [default]
          aws_access_key_id={{ "{{ .access_key }}" }}
          aws_secret_access_key={{ "{{ .secret_key }}" }}
  data:
    - secretKey: access_key
      remoteRef:
        key: {{ .Values.secretPath | quote }}
        property: {{ .Values.properties.accessKey | quote }}
    - secretKey: secret_key
      remoteRef:
        key: {{ .Values.secretPath | quote }}
        property: {{ .Values.properties.secretKey | quote }}
