{{- if .Values.grafana.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.grafana.targetName | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ .Values.secretStore.kind | quote }}
    name: {{ .Values.secretStore.name | quote }}
  target:
    name: {{ .Values.grafana.targetName | quote }}
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: {{ .Values.remoteKey | quote }}
        property: {{ .Values.grafana.userProperty | quote }}
    - secretKey: admin-password
      remoteRef:
        key: {{ .Values.remoteKey | quote }}
        property: {{ .Values.grafana.passwordProperty | quote }}
{{- end }}
{{- if .Values.webhook.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.webhook.targetName | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ .Values.secretStore.kind | quote }}
    name: {{ .Values.secretStore.name | quote }}
  target:
    name: {{ .Values.webhook.targetName | quote }}
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: {{ .Values.remoteKey | quote }}
        property: {{ .Values.webhook.tokenProperty | quote }}
{{- end }}
