---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  gatewayClassName: {{ .Values.gatewayClassName | quote }}
  listeners:
    - name: https
      hostname: {{ .Values.hostname | quote }}
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: {{ .Values.tlsSecretName | quote }}
    - name: http
      hostname: {{ .Values.hostname | quote }}
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
