---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: ghcr.io/stuttgart-things/charts/minio
    chart: minio
    targetRevision: 16.0.10
    helm:
      releaseName: minio
      valuesObject:
        global:
          imageRegistry: ghcr.io
          security:
            allowInsecureImages: true
        image:
          registry: ghcr.io
          repository: stuttgart-things/minio
          tag: 2025.4.22-debian-12-r1
        networkPolicy:
          enabled: true
          allowExternal: true
        auth:
          rootUser: "" # pragma: allowlist secret
          rootPassword: "" # pragma: allowlist secret
        ingress:
          enabled: false
        apiIngress:
          enabled: false
        persistence:
          enabled: true
          storageClass: nfs4-csi
          size: 10Gi
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
