apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - appset-cloudnative-pg.yaml
  - appset-cloudnative-pg-barman.yaml
  - appset-openebs.yaml
  - appset-longhorn.yaml
  - appset-nfs-csi-install.yaml
  - appset-nfs-csi-storageclasses.yaml
