{{- if .Values.authSecret.enabled }}
{{- $defaultName := printf "claim-machinery-api-%s" (sha1sum .Values.destination.server | trunc 8) }}
{{- $appName := .Values.applicationName | default $defaultName }}
{{- $secretValues := dict
      "namespace"  .Values.destination.namespace
      "secretName" .Values.auth.secretName
      "secretKey"  .Values.auth.secretKey
      "token"      .Values.authSecret.homerunAuthToken
}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-auth" $appName | quote }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: {{ .Values.project | quote }}
  source:
    repoURL: {{ .Values.catalog.repoURL | quote }}
    targetRevision: {{ .Values.catalog.targetRevision | quote }}
    path: apps/claim-machinery-api/auth-secret
    helm:
      releaseName: claim-machinery-api-auth
      valuesObject:
        {{- toYaml $secretValues | nindent 8 }}
  destination:
    server: {{ .Values.destination.server | quote }}
    namespace: {{ .Values.destination.namespace | quote }}
  syncPolicy:
    {{- toYaml .Values.syncPolicy | nindent 4 }}
{{- end }}
