apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name | quote }}
rules:
{{- range .Values.rules }}
  - apiGroups: {{ .apiGroups | toJson }}
    resources: {{ .resources | toJson }}
    verbs: {{ default (list "get" "list" "watch") .verbs | toJson }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.name | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | quote }}
    namespace: {{ .Values.serviceAccount.namespace | quote }}
