---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName | quote }}
  namespace: {{ .Values.namespace | quote }}
type: Opaque
immutable: true
stringData:
  masterkey: {{ .Values.values.masterkey | quote }}
