{{- range .Values.components }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .secretName | quote }}
  namespace: {{ $.Values.namespace | quote }}
spec:
  refreshInterval: {{ $.Values.refreshInterval | quote }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $.Values.clusterSecretStoreName | quote }}
  target:
    name: {{ .secretName | quote }}
  data:
    - secretKey: {{ .dataKey | quote }}
      remoteRef:
        key: {{ $.Values.vaultSecretName | quote }}
        property: {{ .vaultProperty | quote }}
{{- end }}
