---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName | quote }}
  namespace: {{ .Values.namespace | quote }}
type: Opaque
stringData:
  APP_TITLE: {{ .Values.values.appTitle | quote }}
  ORGANIZATION_NAME: {{ .Values.values.organizationName | quote }}
  APP_BASE_URL: {{ .Values.values.appBaseURL | quote }}
  BACKEND_BASE_URL: {{ .Values.values.backendBaseURL | quote }}
  CORS_ORIGIN: {{ .Values.values.corsOrigin | quote }}
  AUTH_ENVIRONMENT: {{ .Values.values.authEnvironment | quote }}
  CLAIM_MACHINERY_API_URL: {{ .Values.values.claimMachineryAPIURL | quote }}
  CLAIM_MACHINERY_REGISTRY_URL: {{ .Values.values.claimMachineryRegistryURL | quote }}
  GITHUB_TOKEN: {{ .Values.values.github.token | quote }}
  GITHUB_CLIENT_ID: {{ .Values.values.github.clientId | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.values.github.clientSecret | quote }}
  BACKEND_SECRET: {{ .Values.values.backendSecret | quote }}
  EXTERNAL_ACCESS_TOKEN: {{ .Values.values.externalAccessToken | quote }}
