---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.name | quote }}
spec:
  provider:
    vault:
      server: {{ .Values.server | quote }}
      path: {{ .Values.path | quote }}
      version: {{ .Values.version | quote }}
      caProvider:
        type: {{ .Values.caProvider.type | quote }}
        name: {{ .Values.caProvider.name | quote }}
        namespace: {{ .Values.caProvider.namespace | quote }}
        key: {{ .Values.caProvider.key | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.auth.kubernetes.mountPath | quote }}
          role: {{ .Values.auth.kubernetes.role | quote }}
          serviceAccountRef:
            name: {{ .Values.auth.kubernetes.serviceAccountRef.name | quote }}
            namespace: {{ .Values.auth.kubernetes.serviceAccountRef.namespace | quote }}
