apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-selfsigned-clusterbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: clusterbook.stuttgart-things.com/allocation-ip
              operator: Exists
  template:
    metadata:
      name: cert-manager-selfsigned-{{ .name }}
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: '{{ .name }}'
      destination:
        name: '{{ .name }}'
        namespace: cert-manager
      source:
        repoURL: https://github.com/stuttgart-things/argocd.git
        targetRevision: main
        path: infra/cert-manager/selfsigned
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
