apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-install-clusterbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: clusterbook.stuttgart-things.com/allocation-ip
              operator: Exists
  template:
    metadata:
      name: cert-manager-install-{{ .name }}
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      source:
        repoURL: https://github.com/stuttgart-things/argocd.git
        targetRevision: main
        path: infra/cert-manager/install
        helm:
          valuesObject:
            project: '{{ .name }}'
            destination:
              server: '{{ .server }}'
              namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - ServerSideApply=true
