apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trust-manager-install-clusterbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - clusters:
        selector:
          matchLabels:
            network-platform: "true"
          matchExpressions:
            - key: clusterbook.stuttgart-things.com/allocation-ip
              operator: Exists
            - key: network-platform/trust-manager-install
              operator: NotIn
              values: ["false"]
  template:
    metadata:
      name: trust-manager-install-{{ .name }}
      annotations:
        argocd.argoproj.io/sync-wave: "3"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      source:
        repoURL: https://github.com/stuttgart-things/argocd.git
        # renovate: datasource=github-tags depName=stuttgart-things/argocd
        targetRevision: v0.6.0
        path: infra/trust-manager/install
        helm:
          valuesObject:
            project: '{{ .name }}'
            destination:
              server: '{{ .server }}'
              namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - ServerSideApply=true
