apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-vault-pki-clusterbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - clusters:
        selector:
          matchLabels:
            network-platform: "true"
          matchExpressions:
            - key: clusterbook.stuttgart-things.com/allocation-ip
              operator: Exists
            - key: network-platform/cert-manager-vault-pki
              operator: NotIn
              values: ["false"]
  template:
    metadata:
      name: cert-manager-vault-pki-{{ .name }}
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: '{{ .name }}'
      destination:
        name: '{{ .name }}'
        namespace: cert-manager
      source:
        repoURL: https://github.com/stuttgart-things/argocd.git
        targetRevision: main
        path: infra/cert-manager/vault-pki
        helm:
          valuesObject:
            name: vault-pki
            vault:
              server: '{{ index .metadata.annotations "clusterbook.stuttgart-things.com/vault-server" }}'
              path: '{{ index .metadata.annotations "clusterbook.stuttgart-things.com/vault-pki-path" }}'
              auth:
                tokenSecretRef:
                  name: '{{ index .metadata.annotations "clusterbook.stuttgart-things.com/vault-token-secret" }}'
                  key: token
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - ServerSideApply=true
