apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - appset-cert-manager-install.yaml
  - appset-cert-manager-selfsigned.yaml
  - appset-cert-manager-cluster-ca.yaml
  - appset-cert-manager-vault-pki.yaml
  - appset-cilium-lb.yaml
  - appset-cilium-gateway.yaml
  - appset-cilium-gateway-secondary.yaml
  - appset-trust-manager-install.yaml
  - appset-trust-manager-bundle.yaml
