---
namespace: portal
secretName: backstage-secrets       # pragma: allowlist secret
values:
  appTitle: Stuttgart Things Backstage
  organizationName: stuttgart-things
  appBaseURL: https://backstage.example.com
  backendBaseURL: https://backstage.example.com
  corsOrigin: https://backstage.example.com
  authEnvironment: development
  claimMachineryAPIURL: https://claim-api.example.com
  claimMachineryRegistryURL: https://registry-api.example.com
  github:
    token: ""                       # pragma: allowlist secret
    clientId: ""                    # pragma: allowlist secret
    clientSecret: ""                # pragma: allowlist secret
  backendSecret: ""                 # pragma: allowlist secret
  externalAccessToken: ""           # pragma: allowlist secret
