apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - appset-omni-pitcher-pr-preview.yaml
  - appset-core-catcher-pr-preview.yaml
  - appset-scout-pr-preview.yaml
  - appset-demo-pitcher-pr-preview.yaml
  - appset-policies.yaml
