---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  refreshInterval: {{ .Values.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ .Values.store.name | quote }}
    kind: {{ .Values.store.kind | quote }}
  target:
    name: {{ .Values.secretName | quote }}
    creationPolicy: Owner
  data:
    {{- range .Values.keys }}
    - secretKey: {{ . | quote }}
      remoteRef:
        key: {{ $.Values.secretPath | quote }}
        property: {{ . | quote }}
    {{- end }}
