{{- if .Values.lb.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-lb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: {{ .Values.project | quote }}
  source:
    repoURL: {{ .Values.catalog.repoURL | quote }}
    targetRevision: {{ .Values.catalog.targetRevision | quote }}
    path: infra/cilium/lb-chart
    helm:
      releaseName: cilium-lb
      valuesObject:
        poolName: {{ .Values.lb.poolName | quote }}
        blocks:
          {{- toYaml .Values.lb.blocks | nindent 10 }}
        l2Policy:
          {{- toYaml .Values.lb.l2Policy | nindent 10 }}
  destination:
    server: {{ .Values.destination.server | quote }}
    namespace: {{ .Values.lb.l2Policy.namespace | quote }}
  syncPolicy:
    {{- toYaml .Values.syncPolicy | nindent 4 }}
{{- end }}
