---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/headlamp/
    chart: headlamp
    targetRevision: 0.40.0
    helm:
      releaseName: headlamp
      valuesObject:
        config:
          watchPlugins: true
        pluginsManager:
          enabled: true
          configContent: |
            plugins:
              - name: prometheus
                source: https://github.com/headlamp-k8s/plugins/releases/download/prometheus-0.8.2/prometheus-0.8.2.tar.gz
        httpRoute:
          enabled: true
          parentRefs:
            - name: cilium-gateway
              namespace: default
          hostnames:
            - "headlamp.example.com"
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
